version: '3.8'

services:

  service:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./service:/home
    ports:
      - 20001:20001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
